package model

import (
	"tutoring_server/pkg/logger"
)

// 表与字段注释（PostgreSQL）。COMMENT ON 可重复执行，启动时会确保注释存在。
// 与 migrations/008_schema_optimize.sql 保持一致。
// 写法约定：只写「字段是什么 + 取值枚举 + 必要格式」，业务规则与流程说明留在代码注释里。
var commentSQLs = []string{
	`COMMENT ON TABLE "user" IS '用户表：账号信息、角色、师资身份与会员信息'`,
	`COMMENT ON COLUMN "user".id IS '主键 ID'`,
	`COMMENT ON COLUMN "user".username IS '用户名，唯一，2-32 位'`,
	`COMMENT ON COLUMN "user".password IS '登录密码，bcrypt 加密'`,
	`COMMENT ON COLUMN "user".avatar IS '头像地址'`,
	`COMMENT ON COLUMN "user".phone IS '手机号，登录账号之一'`,
	`COMMENT ON COLUMN "user".email IS '邮箱，选填'`,
	`COMMENT ON COLUMN "user".phone_changed_at IS '最近修改手机号的时间（Unix 秒）'`,
	`COMMENT ON COLUMN "user".user_role IS '使用身份：teacher=老师 parent/personal=学员 org=机构；站长与管理员留空，统一按老师渲染'`,
	`COMMENT ON COLUMN "user".teacher_type IS '师资身份：student=大学生家教 professional=专职老师'`,
	`COMMENT ON COLUMN "user".reg_teacher_type IS '注册时选择的师资身份'`,
	`COMMENT ON COLUMN "user".verified IS '师资身份认证：0=未认证 1=已认证'`,
	`COMMENT ON COLUMN "user".student_card_url IS '学生证照片地址'`,
	`COMMENT ON COLUMN "user".id_card_url IS '身份证照片地址'`,
	`COMMENT ON COLUMN "user".student_verified_at IS '学生身份审核通过时间（Unix 秒）'`,
	`COMMENT ON COLUMN "user".student_expire_at IS '学生身份有效期（毕业时间，Unix 秒）'`,
	`COMMENT ON COLUMN "user".student_expire_notified IS '学生身份到期提醒是否已发送'`,
	`COMMENT ON COLUMN "user".member_expire_notified IS '会员到期提醒是否已发送'`,
	`COMMENT ON COLUMN "user".member_type IS '会员类型：trial=免费试用 daily / monthly / quarterly / yearly=付费会员 permanent=永久会员'`,
	`COMMENT ON COLUMN "user".member_start IS '会员生效时间（Unix 秒）'`,
	`COMMENT ON COLUMN "user".member_expire IS '会员到期时间（Unix 秒）'`,
	`COMMENT ON COLUMN "user".role IS '角色：owner=站长 admin=管理员 user=普通用户'`,
	`COMMENT ON COLUMN "user".status IS '账号状态：normal=正常 frozen=已冻结'`,
	`COMMENT ON COLUMN "user".total_recharge IS '累计充值金额（元）'`,
	`COMMENT ON COLUMN "user".created_at IS '注册时间（Unix 秒）'`,
	`COMMENT ON COLUMN "user".updated_at IS '更新时间（Unix 秒）'`,

	`COMMENT ON TABLE "order" IS '家教订单表：一次辅导需求'`,
	`COMMENT ON COLUMN "order".id IS '主键 ID'`,
	`COMMENT ON COLUMN "order".user_id IS '所属用户 ID，关联 user.id'`,
	`COMMENT ON COLUMN "order".source IS '信息来源'`,
	`COMMENT ON COLUMN "order".published_at IS '订单发布时间，零值表示未填写'`,
	`COMMENT ON COLUMN "order".publisher IS '发布人'`,
	`COMMENT ON COLUMN "order".grade IS '年级'`,
	`COMMENT ON COLUMN "order".order_no IS '订单编号，留空自动生成'`,
	`COMMENT ON COLUMN "order".address IS '上课地址'`,
	`COMMENT ON COLUMN "order".subject IS '辅导科目（单科目）'`,
	`COMMENT ON COLUMN "order".subjects IS '辅导科目多选，JSON 数组字符串'`,
	`COMMENT ON COLUMN "order".content IS '辅导内容'`,
	`COMMENT ON COLUMN "order".student_name IS '学生姓名'`,
	`COMMENT ON COLUMN "order".start_date IS '补课开始日期（Unix 秒）'`,
	`COMMENT ON COLUMN "order".end_date IS '补课结束日期（Unix 秒），0 表示长期'`,
	`COMMENT ON COLUMN "order".total_lessons IS '计划总课时（节），0 表示未填（按补课周期推算）'`,
	`COMMENT ON COLUMN "order".weekly_slots IS '每周上课时段 JSON 数组，例：[{"days":[1,2],"start":"18:00","end":"20:00"}]，days: 1=周一 ... 7=周日'`,
	`COMMENT ON COLUMN "order".hourly_rate IS '时薪（元/小时）'`,
	`COMMENT ON COLUMN "order".bill_mode IS '计费方式：hourly=按小时 lesson=按单次课时 total=按总费用'`,
	`COMMENT ON COLUMN "order".lesson_price IS '单次课时价格（元）'`,
	`COMMENT ON COLUMN "order".total_amount IS '整期总费用（元），按计划总课时分摊到每节'`,
	`COMMENT ON COLUMN "order".direction IS '方向：income=收入 expense=开支；空表示按注册身份推导'`,
	`COMMENT ON COLUMN "order".student_situation IS '学生情况'`,
	`COMMENT ON COLUMN "order".student_gender IS '学生性别：男 / 女'`,
	`COMMENT ON COLUMN "order".contact_phone IS '对方联系电话（收入=学员家长，开支=授课老师）'`,
	`COMMENT ON COLUMN "order".remark IS '备注'`,
	`COMMENT ON COLUMN "order".remark_flag IS '特殊备注标记，true 时课表显示红点'`,
	`COMMENT ON COLUMN "order".status IS '订单状态：pending=未开始 running=进行中 finished=已结束'`,
	`COMMENT ON COLUMN "order".created_at IS '创建时间（Unix 秒）'`,
	`COMMENT ON COLUMN "order".updated_at IS '更新时间（Unix 秒）'`,

	`COMMENT ON TABLE lesson_exception IS '课程例外表：单次课程的改期 / 停课 / 改时间 / 加课'`,
	`COMMENT ON COLUMN lesson_exception.id IS '主键 ID'`,
	`COMMENT ON COLUMN lesson_exception.user_id IS '所属用户 ID，关联 user.id'`,
	`COMMENT ON COLUMN lesson_exception.order_id IS '所属订单 ID，关联 order.id'`,
	`COMMENT ON COLUMN lesson_exception.source_date IS '原定上课日期（Unix 秒）'`,
	`COMMENT ON COLUMN lesson_exception.slot_index IS '对应 weekly_slots 的时段下标（从 0 开始），加课为 -1'`,
	`COMMENT ON COLUMN lesson_exception.type IS '类型：cancel=停课 move=改期 time=仅改时间 extra=临时加课'`,
	`COMMENT ON COLUMN lesson_exception.new_date IS '调整后上课日期（Unix 秒），cancel 时为 0'`,
	`COMMENT ON COLUMN lesson_exception.new_start IS '调整后开始时间 HH:MM，为空沿用订单时段'`,
	`COMMENT ON COLUMN lesson_exception.new_end IS '调整后结束时间 HH:MM'`,
	`COMMENT ON COLUMN lesson_exception.duration_minutes IS '本次课时长度（分钟），0 表示沿用订单时长'`,
	`COMMENT ON COLUMN lesson_exception.note IS '调整原因备注'`,
	`COMMENT ON COLUMN lesson_exception.created_at IS '创建时间（Unix 秒）'`,
	`COMMENT ON COLUMN lesson_exception.updated_at IS '更新时间（Unix 秒）'`,

	`COMMENT ON TABLE lesson IS '历史课次表：已物化的单次课程快照'`,
	`COMMENT ON COLUMN lesson.id IS '主键 ID'`,
	`COMMENT ON COLUMN lesson.user_id IS '所属用户 ID，关联 user.id'`,
	`COMMENT ON COLUMN lesson.order_id IS '所属订单 ID，关联 order.id'`,
	`COMMENT ON COLUMN lesson.order_no IS '订单编号快照'`,
	`COMMENT ON COLUMN lesson.date IS '上课日期 yyyy-mm-dd'`,
	`COMMENT ON COLUMN lesson.weekday IS '星期（1=周一 ... 7=周日）'`,
	`COMMENT ON COLUMN lesson.slot_index IS '时段下标（从 0 开始），临时加课为 -1'`,
	`COMMENT ON COLUMN lesson.start_time IS '开始时间 HH:MM'`,
	`COMMENT ON COLUMN lesson.end_time IS '结束时间 HH:MM'`,
	`COMMENT ON COLUMN lesson.duration_minutes IS '课时时长（分钟）'`,
	`COMMENT ON COLUMN lesson.grade IS '年级快照'`,
	`COMMENT ON COLUMN lesson.student_name IS '学生姓名快照'`,
	`COMMENT ON COLUMN lesson.subject IS '辅导科目快照'`,
	`COMMENT ON COLUMN lesson.address IS '上课地址快照'`,
	`COMMENT ON COLUMN lesson.content IS '辅导内容快照'`,
	`COMMENT ON COLUMN lesson.remark IS '备注快照'`,
	`COMMENT ON COLUMN lesson.remark_flag IS '特殊备注标记快照'`,
	`COMMENT ON COLUMN lesson.hourly_rate IS '时薪快照（元/小时）'`,
	`COMMENT ON COLUMN lesson.status IS '课次状态：regular=常规 canceled=停课 movedOut=已调出 movedIn=已调入 time=仅改时间 extra=临时加课'`,
	`COMMENT ON COLUMN lesson.voided IS '是否已删除：true 时课表与报表隐藏'`,
	`COMMENT ON COLUMN lesson.income IS '本次课时收入（元）'`,
	`COMMENT ON COLUMN lesson.exception_id IS '关联的课程例外 ID，0 表示无'`,
	`COMMENT ON COLUMN lesson.origin_date IS 'movedIn 的原定上课日期 yyyy-mm-dd'`,
	`COMMENT ON COLUMN lesson.origin_weekday IS 'movedIn 的原定星期（1=周一 ... 7=周日）'`,
	`COMMENT ON COLUMN lesson.moved_to_date IS 'movedOut 的调整后日期 yyyy-mm-dd'`,
	`COMMENT ON COLUMN lesson.moved_to_start IS 'movedOut 的调整后开始时间 HH:MM'`,
	`COMMENT ON COLUMN lesson.adjust_note IS '调整原因备注快照'`,
	`COMMENT ON COLUMN lesson.created_at IS '物化写入时间（Unix 秒）'`,
	`COMMENT ON COLUMN lesson.updated_at IS '更新时间（Unix 秒）'`,

	`COMMENT ON TABLE feedback IS '问题反馈表：用户提交的问题与建议'`,
	`COMMENT ON COLUMN feedback.id IS '主键 ID'`,
	`COMMENT ON COLUMN feedback.user_id IS '提交用户 ID，关联 user.id'`,
	`COMMENT ON COLUMN feedback.username IS '提交时用户名快照'`,
	`COMMENT ON COLUMN feedback.content IS '反馈内容，最多 1000 字'`,
	`COMMENT ON COLUMN feedback.contact IS '联系方式，选填'`,
	`COMMENT ON COLUMN feedback.reply IS '官方回复内容'`,
	`COMMENT ON COLUMN feedback.status IS '处理状态：pending=待处理 resolved=已回复'`,
	`COMMENT ON COLUMN feedback.created_at IS '提交时间（Unix 秒）'`,
	`COMMENT ON COLUMN feedback.updated_at IS '更新时间（Unix 秒）'`,

	`COMMENT ON TABLE recharge IS '会员支付记录表：每次开通 / 续费的金额与时长'`,
	`COMMENT ON COLUMN recharge.id IS '主键 ID'`,
	`COMMENT ON COLUMN recharge.user_id IS '账号 ID，关联 user.id'`,
	`COMMENT ON COLUMN recharge.username IS '开通时用户名快照'`,
	`COMMENT ON COLUMN recharge.amount IS '支付金额（元）'`,
	`COMMENT ON COLUMN recharge.period IS '续费时长：monthly / quarterly / yearly / daily'`,
	`COMMENT ON COLUMN recharge.period_name IS '续费时长中文名'`,
	`COMMENT ON COLUMN recharge.days IS '本次增加的天数'`,
	`COMMENT ON COLUMN recharge.member_type IS '开通后的会员类型'`,
	`COMMENT ON COLUMN recharge.before_expire IS '开通前会员到期时间（Unix 秒）'`,
	`COMMENT ON COLUMN recharge.after_expire IS '开通后会员到期时间（Unix 秒）'`,
	`COMMENT ON COLUMN recharge.operator_id IS '操作人 ID，0 表示用户自助'`,
	`COMMENT ON COLUMN recharge.operator_name IS '操作人名称'`,
	`COMMENT ON COLUMN recharge.source IS '来源：admin=后台开通 self=用户自助'`,
	`COMMENT ON COLUMN recharge.remark IS '备注'`,
	`COMMENT ON COLUMN recharge.created_at IS '支付时间（Unix 秒）'`,
	`COMMENT ON COLUMN recharge.updated_at IS '更新时间（Unix 秒）'`,

	`COMMENT ON TABLE price_config IS '会员价格配置表：单行配置，固定 id=1'`,
	`COMMENT ON COLUMN price_config.id IS '主键 ID，固定为 1'`,
	`COMMENT ON COLUMN price_config.pro_monthly_amount IS '专职老师包月价（元）'`,
	`COMMENT ON COLUMN price_config.pro_quarterly_amount IS '专职老师包季价（元）'`,
	`COMMENT ON COLUMN price_config.pro_yearly_amount IS '专职老师包年价（元）'`,
	`COMMENT ON COLUMN price_config.student_discount IS '大学生家教折扣（0-1）'`,
	`COMMENT ON COLUMN price_config.renewal_discount IS '平季续费折扣（0-1）'`,
	`COMMENT ON COLUMN price_config.updated_at IS '更新时间（Unix 秒）'`,

	`COMMENT ON TABLE invite_code IS '邀请码表：管理员生成，注册时与手机号绑定校验'`,
	`COMMENT ON COLUMN invite_code.id IS '主键 ID'`,
	`COMMENT ON COLUMN invite_code.code IS '8 位邀请码，唯一'`,
	`COMMENT ON COLUMN invite_code.phone IS '申请人手机号，同一手机号仅一个邀请码'`,
	`COMMENT ON COLUMN invite_code.used IS '是否已使用：0=未使用 1=已使用'`,
	`COMMENT ON COLUMN invite_code.used_by_id IS '使用的用户 ID，0 表示未使用'`,
	`COMMENT ON COLUMN invite_code.used_at IS '使用时间（Unix 秒），0 表示未使用'`,
	`COMMENT ON COLUMN invite_code.created_at IS '生成时间（Unix 秒）'`,

	`COMMENT ON TABLE message IS '站内信表：广播按接收人各存一条'`,
	`COMMENT ON COLUMN message.id IS '主键 ID'`,
	`COMMENT ON COLUMN message.user_id IS '接收人 ID，关联 user.id'`,
	`COMMENT ON COLUMN message.sender_id IS '发送人 ID，0 表示系统'`,
	`COMMENT ON COLUMN message.sender_name IS '发送人名称快照'`,
	`COMMENT ON COLUMN message.title IS '标题'`,
	`COMMENT ON COLUMN message.content IS '正文'`,
	`COMMENT ON COLUMN message.type IS '类型：system=系统通知 promo=优惠 / 活动'`,
	`COMMENT ON COLUMN message.read_at IS '已读时间（Unix 秒），0 表示未读'`,
	`COMMENT ON COLUMN message.created_at IS '发送时间（Unix 秒）'`,

	`COMMENT ON TABLE student_application IS '大学生家教身份申请表：每次申请一条'`,
	`COMMENT ON COLUMN student_application.id IS '主键 ID'`,
	`COMMENT ON COLUMN student_application.user_id IS '申请人 ID，关联 user.id'`,
	`COMMENT ON COLUMN student_application.username IS '申请人用户名快照'`,
	`COMMENT ON COLUMN student_application.phone IS '申请人手机号快照'`,
	`COMMENT ON COLUMN student_application.invite_code IS '注册时使用的邀请码快照'`,
	`COMMENT ON COLUMN student_application.student_card_url IS '学生证照片地址'`,
	`COMMENT ON COLUMN student_application.id_card_url IS '身份证照片地址'`,
	`COMMENT ON COLUMN student_application.status IS '审核状态：pending=待审核 approved=已通过 rejected=已驳回'`,
	`COMMENT ON COLUMN student_application.expire_at IS '毕业时间（Unix 秒），0 表示未设置'`,
	`COMMENT ON COLUMN student_application.reviewer_id IS '审核人 ID，0 表示未审核'`,
	`COMMENT ON COLUMN student_application.reviewer_name IS '审核人名称快照'`,
	`COMMENT ON COLUMN student_application.remark IS '审核备注'`,
	`COMMENT ON COLUMN student_application.created_at IS '申请时间（Unix 秒）'`,
	`COMMENT ON COLUMN student_application.reviewed_at IS '审核时间（Unix 秒），0 表示未审核'`,
}

// EnsureComments 写入/更新表与字段注释，失败只记日志不影响启动。
func EnsureComments() error {
	for _, sql := range commentSQLs {
		if err := db.Exec(sql).Error; err != nil {
			logger.Error("apply comment failed, sql=%s, err=%s", sql, err.Error())
		}
	}
	return nil
}
